### ISSUE TITLE
sample hangs if Scala 3 is used

### ISSUE THREAD

**Issue by pjfanning** [pjfanning/swagger-pekko-http-sample#3]
Seen with Scala 3.3.4 and 3.5.1. HTTP requests to http://localhost:12345/api-docs/swagger.json hang.

Reported initially by @luksow - https://github.com/theiterators/kebs/issues/282#issuecomment-2419661680

**Comment by pjfanning** [comment]
I have a simpler version of the sample in https://github.com/pjfanning/swagger-pekko-http-sample/tree/scala3 (ie this repo but `scala3` branch).

Use `sbt run` to run the HTTP server and to test use:
`curl -v http://localhost:12345/hello`

This hangs with Scala 3 but switch the build.sbt to Scala 2.13.15 and restart the HTTP server. The curl command then works fine.

Switching to Pekko 1.0 does not alter the result. The Scala 3 hang still happens.

**Comment by pjfanning** [comment]
The hanging thread in the sample has this stacktrace:

```
"pekko-http-sample-pekko.actor.default-dispatcher-8" #147 prio=5 os_prio=31 cpu=69.49ms elapsed=216.75s tid=0x00007fad50fe9800 nid=0xef0b in Object.wait()  [0x000070001273d000]
   java.lang.Thread.State: RUNNABLE
	at com.example.pekko.Rest$.hello(Rest.scala:18)
	at com.example.pekko.Rest$.$init$$$anonfun$2(Rest.scala:21)
	at com.example.pekko.Rest$$$Lambda$8063/0x00000008021fa440.apply(Unknown Source)
	at org.apache.pekko.http.scaladsl.server.Directive$.addByNameNullaryApply$$anonfun$1$$anonfun$1(Directive.scala:184)
	at org.apache.pekko.http.scaladsl.server.Directive$$$Lambda$8064/0x00000008021fb840.apply(Unknown Source)
	at org.apache.pekko.http.scaladsl.server.Directive$.$init$$$anonfun$1(Directive.scala:170)
	at org.apache.pekko.http.scaladsl.server.Directive$$$Lambda$8027/0x00000008021d2040.apply(Unknown Source)
	at org.apache.pekko.http.scaladsl.server.Directive$$anon$1.tapply(Directive.scala:165)
	at org.apache.pekko.http.scaladsl.server.Directive.tflatMap$$anonfun$1$$anonfun$1(Directive.scala:102)
	at org.apache.pekko.http.scaladsl.server.Directive$$Lambda$8065/0x00000008021fc040.apply(Unknown Source)
	at org.apache.pekko.http.scaladsl.server.directives.BasicDirectives.textract$$anonfun$1$$anonfun$1(BasicDirectives.scala:173)
	at org.apache.pekko.http.scaladsl.server.directives.BasicDirectives$$Lambda$8066/0x00000008021fd040.apply(Unknown Source)
	at org.apache.pekko.http.scaladsl.server.directives.BasicDirectives.textract$$anonfun$1$$anonfun$1(BasicDirectives.scala:173)
	at org.apache.pekko.http.scaladsl.server.directives.BasicDirectives$$Lambda$8066/0x00000008021fd040.apply(Unknown Source)
	at org.apache.pekko.http.scaladsl.server.directives.BasicDirectives.mapRouteResultWith$$anonfun$1$$anonfun$1(BasicDirectives.scala:86)
	at org.apache.pekko.http.scaladsl.server.directives.BasicDirectives$$Lambda$8356/0x00000008023ce040.apply(Unknown Source)
	at org.apache.pekko.http.scaladsl.server.directives.BasicDirectives.textract$$anonfun$1$$anonfun$1(BasicDirectives.scala:173)
	at org.apache.pekko.http.scaladsl.server.directives.BasicDirectives$$Lambda$8066/0x00000008021fd040.apply(Unknown Source)
	at org.apache.pekko.http.scaladsl.server.directives.ExecutionDirectives.handleExceptions$$anonfun$1$$anonfun$1(ExecutionDirectives.scala:42)
	at org.apache.pekko.http.scaladsl.server.directives.ExecutionDirectives$$Lambda$8202/0x00000008022bc840.apply(Unknown Source)
	at org.apache.pekko.http.scaladsl.server.Route$.createAsyncHandler$$anonfun$1(Route.scala:127)
	at org.apache.pekko.http.scaladsl.server.Route$$$Lambda$8203/0x00000008022bd040.apply(Unknown Source)
	at org.apache.pekko.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1443)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:555)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:506)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:400)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:662)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:532)
	at org.apache.pekko.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:637)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.org$apache$pekko$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:813)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter$$anon$2.applyOrElse(ActorGraphInterpreter.scala:831)
	at org.apache.pekko.actor.Actor.aroundReceive(Actor.scala:547)
	at org.apache.pekko.actor.Actor.aroundReceive$(Actor.scala:481)
	at org.apache.pekko.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:729)
	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
	at java.util.concurrent.ForkJoinTask.doExec(java.base@11.0.24/ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(java.base@11.0.24/ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(java.base@11.0.24/ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(java.base@11.0.24/ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(java.base@11.0.24/ForkJoinWorkerThread.java:183)
```

**Comment by pjfanning** [comment]
I kept stripping out parts of the code and the issue remained. The final thing that I removed and that then fixed the sample was removing the CORS code in the Rest object. If I remove that, the sample runs ok in Scala 3.

**Comment by jrudolph** [comment]
The problem is that you `Await` in `Rest$`, so you block the class initializer from completing but then there's some weird stuff going on that tries to access the fields (execution context, system) in `Rest$` during request handling and that hangs. So, it's probably related to a different `App` compilation strategy in Scala 3.

**Comment by jrudolph** [comment]
(The stack trace from `jstack` also reference lines in `Rest.scala` that don't exist, so there's definitely something funky...)

**Comment by jrudolph** [comment]
The problem is this:

```
val routes =
    cors()(new HelloService().route)
```

which desugars to something like


```
val routes =
    cors().apply(() => new HelloService(this.executionContext).route)
```

where you recreate the service on every call and therefore close over `Rest$` for accessing the executionContext field leading to the deadlock.
